#!/bin/sh
#
# @name Switch Master Simulink custom simulation
#
#

. ${R}etc/init.d/rc.fw_defaults # default FW parameters

param set-default SIM_GZ_EN 0 # disable Gazebo simulation

# define what to simulate in PX4 and what from simulator:
param set-default SENS_EN_GPSSIM 0
param set-default SENS_EN_MAGSIM 0
param set-default SENS_EN_ARSPDSIM 0
param set-default SENS_EN_BAROSIM 0

param set-default MAV_USEHILGPS 1

param set-default EKF2_MAG_TYPE 0
param set-default ASPD_DO_CHECKS 1
param set-default EKF2_BARO_NOISE 0.1000
param set-default EKF2_DECL_TYPE 3
param set-default EKF2_GPS_CHECK 0
param set-default EKF2_GPS_CTRL 3
param set-default EKF2_GPS_DELAY 0
param set-default EKF2_MAG_CHECK 0
param set-default EKF2_MAG_NOISE 0.0010
param set-default EKF2_MULTI_IMU 1
param set-default EKF2_REQ_EPH 2.0000
param set-default EKF2_REQ_EPV 2.0000
param set-default EKF2_RNG_CTRL 0
param set-default EKF2_RNG_DELAY 0
param set-default EKF2_TERR_MASK 0
param set-default SENS_GPS_MASK 0
param set-default SYS_FAILURE_EN 0

param set-default COM_ARM_BAT_MIN 0.2000
param set-default COM_ARM_EKF_POS 1.0000
param set-default COM_ARM_EKF_VEL 1.0000
param set-default COM_ARM_EKF_YAW 4.0000

param set-default SYS_HITL 1

param set-default FW_LND_ANG 8

param set-default FW_YR_FF 0.3
param set-default FW_YR_I 0.4
param set-default FW_YR_P 0.2

param set-default FW_W_EN 1

param set-default NAV_DLL_ACT 2
param set-default RWTO_TKOFF 1

param set-default CA_AIRFRAME 1

param set-default FD_ACT_EN 0
param set-default FD_ACT_MOT_C2T 0.1000
param set-default FD_ACT_MOT_THR 0.2000
param set-default FD_ACT_MOT_TOUT 1000
param set-default FD_ESCS_EN 1

param set-default SDLOG_PROFILE 27
param set-default SDLOG_UTC_OFFSET 60

param set-default CA_ROTOR_COUNT 6
param set-default CA_METHOD 0
param set-default CA_FAILURE_MODE 1

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_FUNC6 106
param set-default SIM_GZ_EC_DIS1 0
param set-default SIM_GZ_EC_DIS2 0
param set-default SIM_GZ_EC_DIS3 0
param set-default SIM_GZ_EC_DIS4 0
param set-default SIM_GZ_EC_DIS5 0
param set-default SIM_GZ_EC_DIS6 0
param set-default SIM_GZ_EC_MIN1 0
param set-default SIM_GZ_EC_MIN2 0
param set-default SIM_GZ_EC_MIN3 0
param set-default SIM_GZ_EC_MIN4 0
param set-default SIM_GZ_EC_MIN5 0
param set-default SIM_GZ_EC_MIN6 0

param set-default CA_SV_CS_COUNT 6
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS0_TYPE 1
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS1_TYPE 2
param set-default CA_SV_CS2_TRQ_P 1
param set-default CA_SV_CS2_TYPE 3
param set-default CA_SV_CS3_TRQ_Y 1
param set-default CA_SV_CS3_TYPE 4
param set-default CA_SV_CS4_TYPE 9
param set-default CA_SV_CS5_TYPE 10
param set-default CA_SV_CS4_FLAP 1.0000
param set-default CA_SV_CS5_FLAP 1.0000

param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_FUNC4 204
param set-default SIM_GZ_SV_FUNC5 205
param set-default SIM_GZ_SV_FUNC6 206
param set-default SIM_GZ_SV_DIS5 1000
param set-default SIM_GZ_SV_DIS6 1000
param set-default SIM_GZ_SV_MAX5 1000
param set-default SIM_GZ_SV_MAX6 1000
param set-default SIM_GZ_SV_REV 48

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC10 204
param set-default PWM_MAIN_FUNC11 205
param set-default PWM_MAIN_FUNC12 206
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106
param set-default PWM_MAIN_FUNC7 201
param set-default PWM_MAIN_FUNC8 202
param set-default PWM_MAIN_FUNC9 203
param set-default PWM_MAIN_REV 3072


param set-default SDLOG_DIRS_MAX 0
param set-default SDLOG_MODE 0
param set-default SIM_BAT_MIN_PCT 20.0000
param set-default ASPD_FALLBACK_GW 1
param set-default BAT1_CAPACITY 8000.0000
param set-default BAT1_V_CHARGED 4.1000
param set-default BAT1_V_EMPTY 3.2000
param set-default BAT_AVRG_CURRENT 12.0000
param set-default BAT_CRIT_THR 0.1000
param set-default BAT_LOW_THR 0.2000
param set-default CA_ROTOR0_CT 11.0000
param set-default CA_ROTOR0_KM 0.0100
param set-default CA_ROTOR0_PX 0.2000
param set-default CA_ROTOR0_PY 0.1500
param set-default CA_ROTOR1_CT 11.0000
param set-default CA_ROTOR1_KM 0.0100
param set-default CA_ROTOR1_PX 0.2000
param set-default CA_ROTOR1_PY 0.3000
param set-default CA_ROTOR2_CT 11.0000
param set-default CA_ROTOR2_KM 0.0100
param set-default CA_ROTOR2_PX 0.2000
param set-default CA_ROTOR2_PY 0.4500
param set-default CA_ROTOR3_CT 11.0000
param set-default CA_ROTOR3_KM 0.0100
param set-default CA_ROTOR3_PX 0.2000
param set-default CA_ROTOR3_PY -0.1500
param set-default CA_ROTOR4_CT 11.0000
param set-default CA_ROTOR4_KM 0.0100
param set-default CA_ROTOR4_PX 0.2000
param set-default CA_ROTOR4_PY -0.3000
param set-default CA_ROTOR5_CT 11.0000
param set-default CA_ROTOR5_KM 0.0100
param set-default CA_ROTOR5_PX 0.2000
param set-default CA_ROTOR5_PY -0.4500
param set-default CA_R0_SLEW 3.0000
param set-default CA_R1_SLEW 3.0000
param set-default CA_R2_SLEW 3.0000
param set-default CA_R3_SLEW 3.0000
param set-default CA_R4_SLEW 3.0000
param set-default CA_R5_SLEW 3.0000

param set-default FW_AIRSPD_MAX 25.0000
param set-default FW_AIRSPD_MIN 12.0000
param set-default FW_AIRSPD_STALL 10.0000
param set-default FW_AIRSPD_TRIM 18.5000
param set-default FW_GND_SPD_MIN 5.0000
param set-default FW_LND_ABORT 0
param set-default FW_LND_AIRSPD 11.0000
param set-default FW_TKO_AIRSPD 18.0000
param set-default FW_WING_SPAN 2.0000
param set-default MIS_TAKEOFF_ALT 30.0000
param set-default RWTO_NUDGE 0
param set-default WEIGHT_BASE 4.9000
param set-default WEIGHT_GROSS 4.9000
param set-default EKF2_ASPD_MAX 25.0000
param set-default EKF2_GSF_TAS 18.5000
param set-default MIS_TKO_LAND_REQ 0

param set-default FW_FLAPS_TO_SCL 1.0000
param set-default FW_AT_START 0

param set-default FW_PR_FF 0.1578
param set-default FW_PR_I 0.1897
param set-default FW_PR_P 0.1809
param set-default FW_PSP_OFF 5.0000
param set-default FW_P_LIM_MAX 50.0000
param set-default FW_P_TC 0.3548
param set-default FW_RR_FF 0.0432
param set-default FW_RR_I 0.1920
param set-default FW_RR_P 0.1939
param set-default FW_R_TC 0.2482
param set-default FW_THR_SLEW_MAX 0.0000
param set-default FW_THR_TRIM 0.5100
param set-default FW_T_ALT_TC 2.5000
param set-default FW_T_CLMB_MAX 15.0000
param set-default FW_T_CLMB_R_SP 5.0000
param set-default FW_T_I_GAIN_PIT 0.3000
param set-default FW_T_PTCH_DAMP 0.2000
param set-default FW_T_SINK_MAX 10.0000
param set-default FW_T_SINK_MIN 5.0000
param set-default FW_T_SINK_R_SP 5.0000
param set-default FW_T_STE_R_TC 0.1000
param set-default FW_T_TAS_TC 2.0000
param set-default FW_T_THR_INTEG 0.3000
param set-default NAV_FW_ALTL_RAD 10.0000
param set-default NAV_FW_ALT_RAD 20.0000
param set-default NPFG_ROLL_TC 1.0000
param set-default RWTO_ROT_AIRSPD 15.0000
param set-default FD_ACT_EN 0
param set-default FD_ESCS_EN 0
param set-default FW_LND_FLALT 1.0000
param set-default FW_LND_TD_OFF 5.0000
param set-default FW_LND_THRTC_SC 0.8000
param set-default FW_PN_R_SLEW_MAX 60.0000
param set-default FW_T_SEB_R_FF 1.0000
param set-default FW_T_THR_DAMPING 0.3000
param set-default FW_T_VERT_ACC 4.0000
