#!/bin/sh
#
# @name Advanced Plane SITL, main parameters used for Switch Master simulation with Gazebo
#

. ${R}etc/init.d/rc.fw_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=advanced_plane}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_MAGSIM 1
param set-default SENS_EN_ARSPDSIM 1
param set-default SENS_EN_BAROSIM 0

param set-default MAV_USEHILGPS 1

param set-default FW_LND_ANG 8

param set-default FW_YR_FF 0.3
param set-default FW_YR_I 0.4
param set-default FW_YR_P 0.2

param set-default FW_W_EN 1

param set-default NAV_DLL_ACT 2
param set-default RWTO_TKOFF 1
param set-default CA_AIRFRAME 1


param set-default FD_ACT_EN 1
param set-default FD_ACT_MOT_THR 0.2000
param set-default FD_ACT_MOT_TOUT 1000
param set-default FD_ESCS_EN 0
param set-default FD_ACT_MOT_C2T 5.0000
param set-default FD_FAIL_P 70
param set-default FD_FAIL_R 70
param set-default FD_MOT_FAIL_INJ 0

param set-default SDLOG_PROFILE 27
param set-default SDLOG_UTC_OFFSET 60

param set-default CA_ROTOR_COUNT 6
param set-default CA_METHOD 0
param set-default CA_FAILURE_MODE 1

param set-default COM_ARM_CHK_ESCS 1
param set-default COM_ARM_SWISBTN 1
param set-default COM_DISARM_MAN 0
param set-default COM_PREARM_MODE 2
param set-default COM_ARM_EKF_YAW 1.0000
param set-default CBRK_BUZZER 782097

param set-default FW_AT_AXES 7
param set-default MAN_ARM_GESTURE 0
param set-default MNT_MODE_IN 1

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_FUNC6 106
param set-default SIM_GZ_EC_DIS1 0
param set-default SIM_GZ_EC_DIS2 0
param set-default SIM_GZ_EC_DIS3 0
param set-default SIM_GZ_EC_DIS4 0
param set-default SIM_GZ_EC_DIS5 0
param set-default SIM_GZ_EC_DIS6 0
param set-default SIM_GZ_EC_MIN1 0
param set-default SIM_GZ_EC_MIN2 0
param set-default SIM_GZ_EC_MIN3 0
param set-default SIM_GZ_EC_MIN4 0
param set-default SIM_GZ_EC_MIN5 0
param set-default SIM_GZ_EC_MIN6 0

param set-default CA_SV_CS_COUNT 6
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS0_TYPE 1
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS1_TYPE 2
param set-default CA_SV_CS2_TRQ_P 1
param set-default CA_SV_CS2_TYPE 3
param set-default CA_SV_CS3_TRQ_Y 1
param set-default CA_SV_CS3_TYPE 4
param set-default CA_SV_CS4_TYPE 9
param set-default CA_SV_CS5_TYPE 10
param set-default CA_SV_CS4_FLAP 1.0000
param set-default CA_SV_CS5_FLAP 1.0000

param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_FUNC4 204
param set-default SIM_GZ_SV_FUNC5 205
param set-default SIM_GZ_SV_FUNC6 206
param set-default SIM_GZ_SV_DIS5 1000
param set-default SIM_GZ_SV_DIS6 1000
param set-default SIM_GZ_SV_MAX5 1000
param set-default SIM_GZ_SV_MAX6 1000
param set-default SIM_GZ_SV_REV 48

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC10 204
param set-default PWM_MAIN_FUNC11 205
param set-default PWM_MAIN_FUNC12 206
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106
param set-default PWM_MAIN_FUNC7 201
param set-default PWM_MAIN_FUNC8 202
param set-default PWM_MAIN_FUNC9 203
param set-default PWM_MAIN_REV 3072

param set-default SDLOG_DIRS_MAX 0
param set-default SDLOG_MODE 0
param set-default SIM_BAT_MIN_PCT 20.0000
param set-default ASPD_FALLBACK_GW 1

param set-default BAT1_N_CELLS 4
param set-default BAT1_CAPACITY 8000.0000
param set-default BAT_CRIT_THR 0.1500
param set-default BAT_LOW_THR 0.2000
param set-default BAT_EMERGEN_THR 0.1000
param set-default BAT1_V_CHARGED 4.0000
param set-default BAT1_V_EMPTY 3.5000
param set-default BAT_AVRG_CURRENT 10.0000

param set-default CA_ROTOR0_CT 11.0000
param set-default CA_ROTOR0_KM 0.0500
param set-default CA_ROTOR0_PX 0.0000
param set-default CA_ROTOR1_CT 11.0000
param set-default CA_ROTOR1_KM 0.0500
param set-default CA_ROTOR1_PX 0.0000
param set-default CA_ROTOR2_CT 11.0000
param set-default CA_ROTOR2_KM 0.0500
param set-default CA_ROTOR2_PX 0.0000
param set-default CA_ROTOR3_CT 11.0000
param set-default CA_ROTOR3_KM 0.0500
param set-default CA_ROTOR3_PX 0.0000
param set-default CA_ROTOR4_CT 11.0000
param set-default CA_ROTOR4_KM 0.0500
param set-default CA_ROTOR4_PX 0.0000
param set-default CA_ROTOR5_CT 11.0000
param set-default CA_ROTOR5_KM 0.0500
param set-default CA_ROTOR5_PX 0.0000
param set-default CA_ROTOR0_PY -0.8000
param set-default CA_ROTOR1_PY -0.5000
param set-default CA_ROTOR2_PY -0.2700
param set-default CA_ROTOR3_PY 0.2700
param set-default CA_ROTOR4_PY 0.5000
param set-default CA_ROTOR5_PY 0.8000

param set-default FW_AIRSPD_MAX 25.0000
param set-default FW_AIRSPD_MIN 10.0000
param set-default FW_AIRSPD_STALL 9.0000
param set-default FW_AIRSPD_TRIM 16.0000
param set-default FW_GND_SPD_MIN 5.0000
param set-default FW_LND_ABORT 0
param set-default FW_LND_AIRSPD 11.0000
param set-default FW_TKO_AIRSPD 18.0000
param set-default FW_WING_SPAN 2.0000
param set-default MIS_TAKEOFF_ALT 30.0000
param set-default RWTO_NUDGE 0
param set-default WEIGHT_BASE 4.9000
param set-default WEIGHT_GROSS 4.9000
param set-default EKF2_ASPD_MAX 25.0000
param set-default EKF2_GSF_TAS 18.0000
param set-default MIS_TKO_LAND_REQ 0
param set-default ASPD_FS_T_START 1
param set-default EKF2_GPS_CHECK 245
param set-default EKF2_REQ_EPV 5.0000

param set-default FW_FLAPS_TO_SCL 1.0000
param set-default FW_AT_START 0

param set-default FW_PR_FF 0.1578
param set-default FW_PR_I 0.1897
param set-default FW_PR_P 0.1809
param set-default FW_PSP_OFF 5.0000
param set-default FW_P_LIM_MAX 55.0000
param set-default FW_P_TC 0.3548
param set-default FW_RR_FF 0.0432
param set-default FW_RR_I 0.1920
param set-default FW_RR_P 0.1939
param set-default FW_R_TC 0.2482

param set-default FW_THR_SLEW_MAX 0.0000
param set-default FW_THR_TRIM 0.5100
param set-default FW_T_ALT_TC 2.5000
param set-default FW_T_CLMB_MAX 15.0000
param set-default FW_T_CLMB_R_SP 5.0000
param set-default FW_T_I_GAIN_PIT 0.3000
param set-default FW_T_PTCH_DAMP 0.1000
param set-default FW_T_SINK_MAX 10.0000
param set-default FW_T_SINK_MIN 5.0000
param set-default FW_T_SINK_R_SP 5.0000
param set-default FW_T_STE_R_TC 0.1000
param set-default FW_T_TAS_TC 2.0000
param set-default FW_T_THR_INTEG 0.2500
param set-default NAV_FW_ALTL_RAD 10.0000
param set-default NAV_FW_ALT_RAD 20.0000
param set-default RWTO_ROT_AIRSPD 15.0000
param set-default FD_ESCS_EN 0
param set-default FW_LND_FLALT 1.0000
param set-default FW_LND_TD_OFF 5.0000
param set-default FW_LND_THRTC_SC 0.8000
param set-default FW_PN_R_SLEW_MAX 30.0000
param set-default FW_T_SEB_R_FF 1.0000
param set-default FW_T_THR_DAMPING 0.2000
param set-default FW_T_VERT_ACC 4.0000

param set-default BAT1_R_INTERNAL 0.0200
param set-default BAT1_V_EMPTY 3.0000
param set-default COM_DISARM_LAND 0.0000
param set-default COM_FLTT_LOW_ACT 1
param set-default COM_LOW_BAT_ACT 0
param set-default EKF2_REQ_EPH 5.0000
param set-default EKF2_REQ_GPS_H 2.0000
param set-default EKF2_REQ_HDRIFT 0.5000
param set-default EKF2_REQ_SACC 1.0000
param set-default EKF2_REQ_VDRIFT 1.0000

param set-default RTL_DESCEND_ALT 50.0000
param set-default RTL_RETURN_ALT 50.0000
param set-default RTL_TIME_MARGIN 0
param set-default RTL_TYPE 0
param set-default NPFG_SW_DST_MLT 0.2000

param set-default FW_GAMMA1_CLIMB 20.0000
param set-default FW_GAMMA1_SINK 15.0000
param set-default FW_GAMMA2_CLIMB 30.0000
param set-default FW_GAMMA2_SINK -1.0000
param set-default FW_GAMMA3_CLIMB 20.0000
param set-default FW_GAMMA3_SINK 15.0000
param set-default FW_GAMMA5_CLIMB 40.0000
param set-default FW_GAMMA5_SINK 5.0000
param set-default FW_GAMMA6_CLIMB 0.0000
param set-default FW_GAMMA6_SINK 5.0000

param set-default FW_MAN_AMPLITUDE -0.0500
param set-default FW_MAN_DURATION 4.5000
param set-default FW_MAN_EN 1
param set-default FW_MAN_GAMMA_ERR 2.0000
param set-default FW_MAN_PERIOD 0.4000
param set-default FW_MAN_VEL_ERR 0.4000
param set-default FW_MIN_WP_DIST 300.0000
param set-default NAV_DLL_ACT 0
param set-default NAV_RCL_ACT 1
param set-default ACT_MAX_RATE 5.0000

param set-default DELTA_T_R_CS 0.1000
param set-default DELTA_T_Y_CS 0.1000
