#!/bin/sh
#
# @name Switch Master parameters using generic fixed wing airframe
#
# @type Standard Plane
# @class Plane
#
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.fw_defaults

param set-default FW_LND_ANG 8

param set-default FW_W_EN 1

param set-default RWTO_TKOFF 1

param set-default CA_AIRFRAME 1

param set-default FD_ACT_EN 1
param set-default FD_ACT_MOT_THR 0.2000
param set-default FD_ACT_MOT_TOUT 1000
param set-default FD_ESCS_EN 0
param set-default FD_FAIL_P 70
param set-default FD_FAIL_R 70

param set-default SDLOG_PROFILE 27
param set-default SDLOG_UTC_OFFSET 60

param set-default CA_ROTOR_COUNT 6
param set-default CA_METHOD 0
param set-default CA_FAILURE_MODE 1

param set-default CA_SV_CS_COUNT 6
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS0_TYPE 1
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS1_TYPE 2
param set-default CA_SV_CS2_TRQ_P 1
param set-default CA_SV_CS2_TYPE 3
param set-default CA_SV_CS3_TRQ_Y 1
param set-default CA_SV_CS3_TYPE 4
param set-default CA_SV_CS4_TYPE 9
param set-default CA_SV_CS5_TYPE 10
param set-default CA_SV_CS4_FLAP 1.0000
param set-default CA_SV_CS5_FLAP 1.0000

param set-default SDLOG_DIRS_MAX 0
param set-default SDLOG_MODE 0
param set-default SIM_BAT_MIN_PCT 20.0000
param set-default ASPD_FALLBACK_GW 1

param set-default CA_R0_SLEW 3.0000
param set-default CA_R1_SLEW 3.0000
param set-default CA_R2_SLEW 3.0000
param set-default CA_R3_SLEW 3.0000
param set-default CA_R4_SLEW 3.0000
param set-default CA_R5_SLEW 3.0000

param set-default FW_AIRSPD_MAX 25.0000
param set-default FW_AIRSPD_MIN 11.0000
param set-default FW_AIRSPD_STALL 10.0000
param set-default FW_GND_SPD_MIN 5.0000
param set-default FW_LND_ABORT 0
param set-default FW_LND_AIRSPD 11.0000
param set-default FW_WING_SPAN 2.0000
param set-default MIS_TAKEOFF_ALT 30.0000
param set-default WEIGHT_BASE 4.9000
param set-default WEIGHT_GROSS 4.9000
param set-default EKF2_ASPD_MAX 25.0000
param set-default MIS_TKO_LAND_REQ 0

param set-default FW_FLAPS_TO_SCL 1.0000
param set-default FW_AT_START 0

param set-default FW_P_LIM_MAX 50.0000
param set-default FW_THR_SLEW_MAX 0.0000
param set-default FW_T_ALT_TC 2.5000
param set-default FW_T_CLMB_MAX 15.0000
param set-default FW_T_CLMB_R_SP 5.0000
param set-default FW_T_I_GAIN_PIT 0.3000
param set-default FW_T_SINK_MAX 10.0000
param set-default FW_T_SINK_MIN 5.0000
param set-default FW_T_SINK_R_SP 5.0000
param set-default FW_T_STE_R_TC 0.1000
param set-default FW_T_TAS_TC 3.0000
param set-default NAV_FW_ALTL_RAD 10.0000
param set-default NAV_FW_ALT_RAD 20.0000
param set-default RWTO_ROT_AIRSPD 15.0000
param set-default FD_ACT_EN 0
param set-default FD_ESCS_EN 0
param set-default FW_LND_FLALT 1.0000
param set-default FW_LND_TD_OFF 5.0000
param set-default FW_LND_THRTC_SC 0.8000
param set-default FW_PN_R_SLEW_MAX 30.0000
param set-default FW_T_SEB_R_FF 1.0000
param set-default FW_T_VERT_ACC 4.0000
param set-default ASPD_DO_CHECKS 3

param set-default BAT1_N_CELLS 4
param set-default BAT1_CAPACITY 8000.0000
param set-default BAT1_V_CHARGED 4.0000
param set-default BAT1_V_EMPTY 3.5000
param set-default BAT_AVRG_CURRENT 20.0000

param set-default CA_ROTOR0_KM 0.0500
param set-default CA_ROTOR0_PX 0.1000
param set-default CA_ROTOR0_PY 0.0000
param set-default CA_ROTOR1_KM 0.0500
param set-default CA_ROTOR1_PX 0.1000
param set-default CA_ROTOR1_PY 0.0000
param set-default CA_ROTOR2_KM 0.0500
param set-default CA_ROTOR2_PX 0.1000
param set-default CA_ROTOR2_PY 0.0000
param set-default CA_ROTOR3_KM 0.0500
param set-default CA_ROTOR3_PX 0.1000
param set-default CA_ROTOR3_PY 0.0000
param set-default CA_ROTOR4_KM 0.0500
param set-default CA_ROTOR4_PX 0.1000
param set-default CA_ROTOR4_PY 0.0000
param set-default CA_ROTOR5_KM 0.0500
param set-default CA_ROTOR5_PX 0.1000
param set-default CA_ROTOR5_PY 0.0000


param set-default CA_SV_CS2_TRIM -0.1000
param set-default COM_ARM_EKF_VEL 0.7000
param set-default COM_ARM_MAG_ANG 90
param set-default COM_ARM_SWISBTN 1
param set-default COM_FLTMODE1 0
param set-default COM_FLTMODE4 4
param set-default COM_FLTMODE6 3
param set-default COM_FLTT_LOW_ACT 1
param set-default COM_OF_LOSS_T 0.5000
param set-default COM_POS_FS_EPH 15.0000
param set-default COM_RC_IN_MODE 0
param set-default COM_RC_LOSS_T 1.0000
param set-default COM_VEL_FS_EVH 5.0000
param set-default EKF2_BCOEF_X 25.0000
param set-default EKF2_BCOEF_Y 25.0000
param set-default EKF2_EVA_NOISE 0.0500
param set-default EKF2_EV_DELAY 175.0000
param set-default EKF2_GND_EFF_DZ 0.0000
param set-default EKF2_GPS_POS_X 0.1440
param set-default EKF2_GPS_POS_Y 0.0300
param set-default EKF2_GPS_POS_Z -0.0600
param set-default EKF2_GSF_TAS 18.0000
param set-default EKF2_RNG_QLTY_T 1.0000
param set-default EKF2_TAS_GATE 3.0000
param set-default FD_ACT_MOT_C2T 5.0000
param set-default FW_AIRSPD_TRIM 18.0000
param set-default FW_AT_AXES 7
param set-default FW_MAN_P_MAX 55.0000
param set-default FW_MAN_R_MAX 55.0000
param set-default FW_THR_TRIM 0.6000
param set-default FW_TKO_AIRSPD 15.0000
param set-default IMU_GYRO_CUTOFF 30.0000
param set-default LNDFW_VEL_Z_MAX 5.0000
param set-default MAN_ARM_GESTURE 0
param set-default MAV_0_RATE 57600
param set-default MAV_PROTO_VER 2
param set-default MNT_MODE_IN 1
param set-default MPC_XY_CRUISE 20.0000
param set-default NAV_DLL_ACT 0
param set-default NAV_RCL_ACT 2

param set-default PWM_MAIN_DIS2 1550
param set-default PWM_MAIN_DIS3 1425
param set-default PWM_MAIN_DIS4 1500
param set-default PWM_MAIN_DIS7 1500
param set-default PWM_MAIN_DIS8 1500
param set-default PWM_MAIN_MAX3 1850
param set-default PWM_MAIN_MIN3 1070

param set-default PWM_MAIN_FUNC1 201
param set-default PWM_MAIN_FUNC2 203
param set-default PWM_MAIN_FUNC3 204
param set-default PWM_MAIN_FUNC4 202
param set-default PWM_MAIN_FUNC5 205
param set-default PWM_MAIN_FUNC6 206
param set-default PWM_MAIN_FUNC7 0
param set-default PWM_MAIN_FUNC8 0

param set-default PWM_MAIN_MAX5 1600
param set-default PWM_MAIN_MIN6 1400
param set-default PWM_MAIN_REV 3094
param set-default PWM_MAIN_TIM0 50
param set-default PWM_MAIN_TIM1 50
param set-default PWM_MAIN_TIM2 50

param set-default RTL_DESCEND_ALT 30.0000
param set-default RTL_RETURN_ALT 30.0000
param set-default RTL_TYPE 0
param set-default RWTO_NUDGE 1
param set-default SDLOG_MISSION 1
param set-default SENS_EN_MS4525DO 1
param set-default SENS_IMU_MODE 1
param set-default SYS_FAILURE_EN 1
param set-default TEL_BST_EN 1

param set-default UAVCAN_EC_FUNC1 101
param set-default UAVCAN_EC_FUNC2 102
param set-default UAVCAN_EC_FUNC3 103
param set-default UAVCAN_EC_FUNC4 104
param set-default UAVCAN_EC_FUNC5 105
param set-default UAVCAN_EC_FUNC6 106
param set-default UAVCAN_ENABLE 3
param set-default UAVCAN_NODE_ID 21

param set-default COM_DISARM_LAND 0.0000
param set-default COM_FLTT_LOW_ACT 1
param set-default COM_LOW_BAT_ACT 0
param set-default RTL_DESCEND_ALT 50.0000
param set-default RTL_RETURN_ALT 50.0000
param set-default RTL_TIME_MARGIN 0
param set-default RTL_TYPE 0
param set-default NPFG_SW_DST_MLT 0.2000
param set-default FW_MIN_WP_DIST 300.0000

param set-default CA_ROTOR0_PY -0.2700
param set-default CA_ROTOR1_PY -0.5000
param set-default CA_ROTOR2_PY -0.8000
param set-default CA_ROTOR3_PY 0.2700
param set-default CA_ROTOR4_PY 0.5000
param set-default CA_ROTOR5_PY 0.8000

param set-default COM_PREARM_MODE 2
param set-default COM_RCL_EXCEPT 0

param set-default ASPD_SCALE_APPLY 0
param set-default BAT_CRIT_THR 0.0500
param set-default BAT_EMERGEN_THR 0.0300
param set-default BAT_LOW_THR 0.1200
param set-default FW_GAMMA1_CLIMB 0.0000
param set-default FW_GAMMA1_SINK 0.0000
param set-default FW_GAMMA3_CLIMB 20.0000
param set-default FW_GAMMA3_SINK 15.0000
param set-default FW_GAMMA4_CLIMB 30.0000
param set-default FW_GAMMA4_SINK -1.0000
param set-default FW_GAMMA6_CLIMB 40.0000
param set-default FW_GAMMA6_SINK 5.0000
param set-default FW_MAN_AMPLITUDE -0.2000
param set-default FW_MAN_DURATION 4.5000
param set-default FW_MAN_EN 1
param set-default FW_MAN_GAMMA_ERR 2.0000
param set-default FW_MAN_PERIOD 0.4000
param set-default FW_MAN_VEL_ERR 0.4000
param set-default FW_T_PTCH_DAMP 0.1000
param set-default FW_T_THR_DAMPING 0.1000
param set-default FW_T_THR_INTEG 0.1000
param set-default RTL_TIME_FACTOR 1.0000

param set-default BAT2_CAPACITY 8000.0000
param set-default BAT2_N_CELLS 4
param set-default BAT2_R_INTERNAL 0.2000
param set-default BAT2_V_CHARGED 4.0000
param set-default BAT2_V_EMPTY 3.5000
param set-default BAT2_V_LOAD_DROP 0.5000
param set-default FW_MAN_TRIM_TIME 0.2000
param set-default NPFG_DAMPING 0.6000
param set-default ACT_MAX_RATE 10.0000

param set-default DELTA_T_R_CS 0.1000
param set-default DELTA_T_Y_CS 0.1000

param set-default BAT1_R_INTERNAL -1.0000
param set-default BAT1_V_LOAD_DROP 0.3000
param set-default CA_SV_CS0_TRIM 0.0700
param set-default CA_SV_CS2_TRIM 0.0700
param set-default CA_SV_CS3_TRIM 0.1200
param set-default CA_SV_CS4_TRIM 0.2600
param set-default CA_SV_CS5_TRIM 0.4000
param set-default FW_PR_FF 0.3144
param set-default FW_PR_I 0.1210
param set-default FW_PR_P 0.1166
param set-default FW_P_TC 0.4514
param set-default FW_RR_FF 0.2114
param set-default FW_RR_I 0.1212
param set-default FW_RR_P 0.1183
param set-default FW_R_TC 0.3453
param set-default FW_YR_FF 0.2815
param set-default FW_YR_I 0.1215
param set-default FW_YR_P 0.1210
param set-default PWM_MAIN_DIS1 1500
param set-default PWM_MAIN_DIS5 1515
param set-default PWM_MAIN_DIS6 1520
param set-default PWM_MAIN_MAX1 1850
param set-default PWM_MAIN_MIN1 1100
param set-default PWM_MAIN_MIN2 1170
